
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: contenteditor
  namespace: fuze
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: contenteditor
    spec:
      containers:
      - name: contenteditor
        image: 329054710135.dkr.ecr.eu-west-2.amazonaws.com/rm_contenteditor:latest
        ports:
        - containerPort: 8080